#!/bin/bash
#
# Copyright © 2026 Guillaume AGNIERAY
#
# This script is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

set -e

# Initialize variables with default values
OPALE_BASE="master"
INCLUDE_PLUGINS="no"
PACKAGE_NAME="opale_customized"
PACKAGE_VERSION=""

# Define color codes
COLOR_RESET="\033[0m"
COLOR_GREEN="\033[32m"
COLOR_BLUE="\033[34m"
COLOR_RED="\033[31m"

# Function to print help/usage instructions
help() {
    echo -e "${COLOR_GREEN}Usage:${COLOR_RESET} ./$(basename "$0") [OPTIONS] <COMMAND>\n"

    echo -e "${COLOR_GREEN}Options:${COLOR_RESET}"
    echo -e "  -b BASE     Opale base branch to use (default: master)"
    echo -e "  -n NAME     Package name (default: opale_customized)"
    echo -e "  -p yes/no   Include plugins stylesheets (default: no)"
    echo -e "  -v VERSION  Package version (optional)"
    echo -e "  -h          Display this help message\n"

    echo -e "${COLOR_GREEN}Commands:${COLOR_RESET}"
    echo -e "  package     Build and package the theme into a .tar.gz archive"
    echo -e "  help        Display this help message\n"

    echo -e "${COLOR_GREEN}Examples:${COLOR_RESET}"
    echo -e "  ./$(basename "$0") -b redmine-5.x -p yes"
    echo -e "  ./$(basename "$0") -n my_theme -v 1.0.0 package"
    echo -e "  ./$(basename "$0") -b redmine-6.x -n custom_theme -v 2.1.0 package\n"

    echo -e "${COLOR_GREEN}Notes:${COLOR_RESET}"
    echo -e "  - Options must be placed before the command"
    echo -e "  - Version is optional; if provided, it's appended to the package name"
    echo -e "  - The script must be run from the project root directory"
}

# Check for help flag early
if [[ "$1" == "-h" || "$1" == "help" ]]; then
    help
    exit 0
fi

# Read options and corresponding values
while getopts "b:n:p:v:h" option; do
    case "$option" in
        b) OPALE_BASE=${OPTARG};;
        n) PACKAGE_NAME=${OPTARG};;
        p) INCLUDE_PLUGINS=${OPTARG};;
        v) PACKAGE_VERSION=${OPTARG};;
        h) help; exit 0;;
        *) help; exit 1;;
    esac
done

# Remove processed options from arguments
shift $((OPTIND - 1))

# Define full package name
if [ -n "${PACKAGE_VERSION}" ]; then
    FULL_PACKAGE_NAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
else
    FULL_PACKAGE_NAME=${PACKAGE_NAME}
fi

# Function to build the customized theme
build_theme() {
    # Check requirements
    echo -e "${COLOR_BLUE}Checking npm version...${COLOR_RESET}"
    if ! npm -v --silent; then
        echo -e "${COLOR_RED}Install Node.js and npm!${COLOR_RESET}"
        exit 1
    fi
    echo -e "\n${COLOR_BLUE}Checking git version...${COLOR_RESET}"
    if ! git -v; then
        echo -e "${COLOR_RED}Install git!${COLOR_RESET}"
        exit 1
    fi

    # Start build
    echo -e "\n${COLOR_BLUE}Building customized theme based on Opale in the 'dist/' directory...${COLOR_RESET}\n"
    rm -rf dist/*/
    mkdir -p dist/"${FULL_PACKAGE_NAME}"
    cd src/opale
    if [ "${OPALE_BASE}" != "master" ] ; then
        git switch "${OPALE_BASE}"
    fi
    npm install --silent

    # Add custom variables to application.scss
    cp ../_custom-variables.scss src/sass
    if ! head -1 src/sass/application.scss | grep -q '^@use "custom-variables";'; then
        echo -e "Info: adding @use rule at the top of 'opale/src/sass/application.scss'"
        { echo '@use "custom-variables";'; cat src/sass/application.scss; } > temp && mv temp src/sass/application.scss
    else
        echo -e "Info : @use rule already at the top of 'opale/src/sass/application.scss'"
    fi

    # Build and copy in dist folder
    npm run lint
    npm run build
    if [ -d "../favicon" ]; then
      cp -r ../favicon ../../dist/"${FULL_PACKAGE_NAME}"
    fi
    if [ -d "../images" ]; then
      cp -r ../images ../../dist/"${FULL_PACKAGE_NAME}"
    fi
    if [ -d "javascripts" ]; then
      cp -r javascripts ../../dist/"${FULL_PACKAGE_NAME}"
    fi
    if [ "${INCLUDE_PLUGINS}" == "yes" ]; then
      cp -r plugins ../../dist/"${FULL_PACKAGE_NAME}"
    fi
    cp -r webfonts stylesheets ../../dist/"${FULL_PACKAGE_NAME}"
    if [ -d "../webfonts" ]; then
      cp ../webfonts/* ../../dist/"${FULL_PACKAGE_NAME}"/webfonts
    fi
    cp ../README.md ../../LICENSE ../../dist/"${FULL_PACKAGE_NAME}"

    # Restore Opale
    git restore .
    if [ "${OPALE_BASE}" != "master" ] ; then
        git switch master
    fi
    rm src/sass/_custom-variables.scss
    rm -rf node_modules
    echo -e "\n${COLOR_GREEN}Customized theme built successfully!${COLOR_RESET}"
}

# Function to package the customized theme
package_theme() {
    build_theme
    echo -e "\n${COLOR_BLUE}Packaging customized theme based on Opale in the 'dist/' directory...${COLOR_RESET}\n"
    cd ../../dist
    tar cvfz "${FULL_PACKAGE_NAME}".tar.gz "${FULL_PACKAGE_NAME}"
    rm -rf "${FULL_PACKAGE_NAME}"
    echo -e "\n${COLOR_GREEN}Customized theme packaged successfully!${COLOR_RESET}"
}

# Handle commands
case $1 in
    package) package_theme;;
    help) help;;
    "") build_theme;;
    *) echo -e "Unknown command: $1"; help; exit 1;;
esac
